version = 0.1

[dev.build.parameters]
template_file = "template.yaml"
build_dir = ".aws-sam/dev/"

[dev.deploy.parameters]
template_file = ".aws-sam/dev/template.yaml"
stack_name = "cross-stack-sam"
s3_bucket = "cross-stack-sam"
s3_prefix = "dev/hello"
region = "ap-northeast-1"
profile = "default"
confirm_changeset = false
capabilities = ["CAPABILITY_NAMED_IAM", "CAPABILITY_AUTO_EXPAND"]
parameter_overrides = "Env=dev"


[prod.build.parameters]
template_file = "template.yaml"
build_dir = ".aws-sam/prod"

[prod.deploy.parameters]
template_file = ".aws-sam/prod/template.yaml"
stack_name = "cross-stack-sam"
s3_bucket = "cross-stack-sam"
s3_prefix = "prod/hello"
region = "ap-southeast-1"
profile = "default"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
