AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: for all Lambda

Parameters:
  Env:
    Description: env
    Type: String
    Default: dev
  RoleForLambda:
    Description: Lambda用Role
    Type: String
    Default: arn:aws:iam::{ID}:role/service-role/{Role_name}

Resources:

  Lambda:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: lambda/template.yaml
      Parameters:
        Env: !Ref Env
        RoleForLambda: !Ref RoleForLambda

Outputs:
  LineSolutionPointcard:
    Value: !GetAtt LineSolutionPointcard.Outputs.Arn
    Description: Arn
