# Lambdaコンテナイメージ用
FROM public.ecr.aws/lambda/python:3.7

COPY app.py requirements.txt fetch-headless-chrome.sh ./

RUN python3.7 -m pip install --upgrade pip
RUN python3.7 -m pip install -r requirements.txt -t .

WORKDIR /opt
COPY fetch-headless-chrome.sh ./
RUN sh fetch-headless-chrome.sh

# Command can be overwritten by providing a different command in the template directly.
CMD ["app.lambda_handler"]
